name: NPM install
description: Run NPM install

inputs:
  node_version:
    description: "Possible node version (default: 18)"
    required: false
    default: "18"
  node_auth_token:
    description: "The Github Personal Access Token to access npm"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        node-version: ${{ inputs.node_version }}
        scope: "@elseu"
        registry-url: https://npm.pkg.github.com/

    - run: npm ci
      env:
        PNODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
      shell: bash
